# Copyright 2024-2025 Amazon.com, Inc. or its affiliates.

FROM public.ecr.aws/lambda/python:3.12 as build

# Build time arguments
ARG BUILD_CERT=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
ARG PIP_INSTALL_LOCATION=https://pypi.org/simple/
ARG MINICONDA_VERSION=Miniconda3-latest-Linux-x86_64
ARG MINICONDA_URL=https://repo.anaconda.com/miniconda/${MINICONDA_VERSION}.sh
ARG CONDA_ENV_NAME="osml_geo_agents"

# Define required packages to install
ARG PACKAGES="wget"

# Give sudo permissions
USER root

# Configure, update, and refresh yum environment
RUN dnf -y upgrade && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Install all our dependencies
RUN dnf install -y $PACKAGES

# Clean up after installing $PACKAGES
RUN rm -rf /var/cache/yum

# Install Miniconda
RUN wget -c ${MINICONDA_URL} && \
    chmod +x ${MINICONDA_VERSION}.sh && \
    ./${MINICONDA_VERSION}.sh -b -f -p /opt/conda && \
    rm ${MINICONDA_VERSION}.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

# Add conda to the path
ENV PATH=/opt/conda/bin:$PATH

# Copy conda ENV
COPY conda/agent-environment.yml ${LAMBDA_TASK_ROOT}/environment.yml

# Install python with conda and remove additional unnecessary files
RUN conda env create -n ${CONDA_ENV_NAME} --file environment.yml && \
    conda clean -afy && \
    rm -rf /opt/conda/pkgs

# Stage 2: Runtime environment
FROM public.ecr.aws/lambda/python:3.12 as deploy

# Add conda to the path
ENV CONDA_ENV_NAME="osml_geo_agents"
ENV PATH=/opt/conda/bin:$PATH
ENV PYTHONPATH=/opt/conda/envs/${CONDA_ENV_NAME}/bin

# Copy the conda environment from the build stage
# We now replace the image’s existing Python with Python from the conda environment:
COPY --from=build /opt/conda /opt/conda
RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

#SHELL ["conda", "run", "--no-capture-output", "-n", "osml_geo_agents", "/bin/bash", "-c"]

RUN rm -rf /var/lang/bin/python3.12 && \
    ln -sf /opt/conda/envs/${CONDA_ENV_NAME}/bin/python /var/lang/bin/python3.12

# Copy the function code to the LAMBDA_TASK_ROOT directory
ADD . ${LAMBDA_TASK_ROOT}

# Install the custom code into the conda environment
RUN conda run --no-capture-output -n ${CONDA_ENV_NAME} python3.12 -m pip install --no-cache-dir ${LAMBDA_TASK_ROOT}

# Set entry point to use the conda environment. This should match the entrypoint
CMD ["aws.osml.geoagents.handler"]
