name: Bedrock Code Review

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_GITHUB_ACCOUNT_NUMBER }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-duration-seconds: 7200
      - name: PR review
        uses: tmokmss/bedrock-pr-reviewer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          disable_release_notes: true
          bedrock_light_model: ${{ vars.BEDROCK_LIGHT_MODEL }}
          bedrock_heavy_model: ${{ vars.BEDROCK_HEAVY_MODEL }}
