# This workflow will install npm dependencies and perform linting of CDK code

name: cdk

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: cdk/package-lock.json
      - name: Install dependencies
        run: cd cdk && npm ci || exit 1
      - name: Lint
        run: cd cdk && npm run lint
      - name: Format check
        run: cd cdk && npm run format:check
